### ISSUE TITLE
請問如何開發好用程式

### ISSUE THREAD

**Issue by yenin1018** [kevin940726/BeanfunLogin#12]
你好~
想請問做這種登入器，要先知道它BF登入模式嗎

可以提點一些方向，不知道要從何下手。

請問你的程式可以參考嗎?

**Comment by xnum** [comment]
理論面要了解HTTP(S) request / response (特別是header) 和 cookie
模擬HTTP POST封包
實務上就是監聽觀察瀏覽器與伺服器的互動 看原始碼 看request如何構造
chrome的development tools對這方面有很大幫助

**Comment by kevin940726** [comment]
對於此專案而言重點就只在於封包的擷取，至於程式語言的部分是我用一個很不熟的語言在短時間內沒有測試的情況下寫的，所以不建議參考我的程式碼哦，倒是如 @xnum 所說的學會理論面的比較重要。

Not related to the project, closed.

**Comment by yenin1018** [comment]
恩恩，感謝 兩位分享

原來是封包收集分析，我比較不懂封包一些概念

要再研究研究

通常會有加密會比較看不出來，是使用哪種加密方式嗎

這次看您的說法也是跟密碼加密有關西

哈~ 我只會簡單程式  概念還要加強加強 ， 感謝分享囉
