### ISSUE TITLE
vm beanfunlogin讀取太慢

### ISSUE THREAD

**Issue by qwe3319543** [kevin940726/BeanfunLogin#15]
你好大大 
我用vmplayer開楓之谷
開beanfunlogin時工作管理員有出現 但是要過幾分鐘才會出現程式
有辦法解決嗎

先求1.6.3版本

主電腦用傳統登入器是秒開的

**Comment by kevin940726** [comment]
Sorry I have no idea how to fix this problem since I haven't try it in VM ever before.
