### ISSUE TITLE
建議預設要求系統管理員權限

### ISSUE THREAD

**Issue by jh961202** [kevin940726/BeanfunLogin#16]
由於MS的NGS會需要系統管理員權限，不然會跳錯誤訊息，可否在此程式啟動時就直接要求系統管理員的權限？（開啟後會跳UAC確認視窗的那種）

**參考：http://stackoverflow.com/questions/7666408/how-to-request-administrator-permissions-when-the-program-starts

**Comment by xnum** [comment]
我不太清楚您所說的MS需要這個權限與此程式的關聯性；
是指此程式使用自動開啟遊戲功能時，所開啟的MS會無法正常啟動嗎？
能否提供您的作業系統版本以供參考，感謝。

**Comment by jh961202** [comment]
如果沒有以系統管理員身分執行這個程式時，MS就會發生「因為沒有以系統管理員身分執行」的錯誤訊息（「NGS初始化錯誤」那類的）。因為使用系統管理員身分執行登入器後，登入器再去呼叫其他程式，就都會是以系統管理員身分去呼叫並執行，於是就不會發生錯誤。
（OS=Win7 x64 SP1，不過Win10 v1511 x64如果不以系統管理員身分執行時，也會這樣）

**Comment by kevin940726** [comment]
我記得我很久以前加過自動要求系統管理者權限
sorry 我已經沒有再維護這個 project 
有問題歡迎詢問 @xnum 或是送 PR 哦 😃

**Comment by xnum** [comment]
之前做過測試 一般登入OK 但是PS卡登入就爛掉了
如果在相容性設定勾選用系統管理員開啟也可以達到相同功能
所以目前是不考慮寫這個進去
