### ISSUE TITLE
Inject a ga script?

### ISSUE THREAD

**Issue by kevin940726** [kevin940726/BeanfunLogin#17]
I wonder how many users (and other analysis) are using this program. As traffic on github page, there are already 1600 unique visitors until this day only in this year. Maybe injecting a ga script to track the actual program?

Of course some proper announcement should be made before people download it (people tend to be sensitive about any kind of tracking features...). Let me know what anyone think about this?

**Comment by xnum** [comment]
webclient只有做HTTP操作 沒有執行script 所以直接埋進去沒有作用
加上檢查版本的網址在github 能做的事情很有限
把網址改成自己host的主機比較能做到其他事情 (夾帶本機資訊POST出去)
如果只是修改這方面的code就丟出新版本給使用者 我猜更新意願應該不高
不過最近有個QRCode login可以試著做看看 這個功能卡關中...

**Comment by kevin940726** [comment]
how about [this](https://developers.google.com/api-client-library/dotnet/apis/analytics/v3?hl=zh-TW)?
沒有仔細看過不過原理上來說是可行的吧

我也認同只是做這樣的確不會有人更新
QRCode可以考慮放進去
或是加個斷線重登的小功能進去
程式本身似乎也沒什麼重大問題需要更新的?

**Comment by xnum** [comment]
應該可行
這邊有個[repo](https://github.com/AttackPattern/CSharpAnalytics)做了這件事

GAMAOTP要停用了 或許可以移除掉
其他沒什麼問題

**Comment by kevin940726** [comment]
@xnum 你最近有空做這些事嗎?
我可能還需要幾天才能重新把環境架好 :joy: 
若你想做的話可以直接開始

**Comment by xnum** [comment]
這邊有個我寫的QRCode Login程式碼
[link](https://github.com/xnum/BeanfunLogin/commit/c4f93245f1c8c8f359c9790087d1f31dd463e33a)
但執行到GET qr_step2.aspx
Server端會回傳error頁而不是final_step.aspx
我檢查了蠻久都找不到原因
或許您可以從這邊接手研究看看

**Comment by kevin940726** [comment]
@xnum 我做了一個working [demo](https://github.com/kevin940726/bflogin-qrcode)
但是用 Node.js 寫的
我測試是可以成功登入拿到帳號清單的
而我們的步驟邏輯也幾乎都一樣
我也找不到到底哪裡出錯了 😞 
希望你能突破我們的盲點

**Comment by xnum** [comment]
我檢查了一輪整個流程 與您寫的相同
chrome裡的http request header和程式debug印出來的相同
最壞的情況只能猜測是有執行甚麼javascript或實作上的不同了
如果用node 其內部實作有多作哪些事情嗎 例如header, 執行網頁的javascript...

**Comment by kevin940726** [comment]
header沒變
也沒有執行任何client的js
比較特別的一點是我用的 request 套件可以自動 redirect 所有請求
其他我真的看不出來有什麼差...

**Comment by xnum** [comment]
我看到webclient比較特殊的是它會用到Expect: 100-continue這東西
而302 Found除非我手動關掉 不然也是會自動重導向的
所以真的很奇怪 或許可以試試看nodejs的版本 能否把流程simplify
至少可以縮小debug範圍 我在chrome上測試的時候 是沒有做POST的
直接get qr_form的那頁就能拿到qrcode的src

**Comment by xnum** [comment]
現在是這樣 
網頁操作流程是對的 Cookie也是對的 header重要的幾個也仿造上去了
Server side剩下可能的檢測手段只有javascript 我先前一直以為是這個問題
當確定不是js的問題 我覺得可以試試看更換成別的http client implementation
不過這也是我很討厭的 MS的東西都不給人看實作細節
或許要找個第三方開源函式庫來試試看 或是偷偷呼叫nodejs解決掉 XDD

**Comment by kevin940726** [comment]
噢噢那個POST是我還在測試的時候上的
後面忘記刪掉 那段的確沒有用XD

我贊同找另外的 http client library XD
我真的跟 C# 很不熟所以是直接用了原生的
呼叫 node 應該是不用考慮了 倒不如呼叫 curl 做掉算了XD
你可以幫忙 survey 一點這方面的套件嗎

**Comment by xnum** [comment]
稍微找了一下 似乎沒有專門處理這個部分的
只有看到一套[EasyHTTP](https://github.com/EasyHttp/EasyHttp)
但也是基於.net的核心API 這套是用httpwebrequest為基礎
用libcurl的話就是要自己處理cookie header
[這邊](http://stackoverflow.com/questions/15136952/can-i-communicate-between-c-sharp-application-and-node-js-code)有一些node的作法 用REST或TCP來溝通感覺上是可行的

**Comment by xnum** [comment]
okay..我找到問題了 有個地方skey被洗掉 所以它拿了錯誤的skey去比對
https://github.com/xnum/BeanfunLogin/commit/d61b5c03704b6d11014d1a1bd5c92292139b7305
可以走到final_step了

**Comment by xnum** [comment]
現在可以成功拿到帳號列表 但是在GetOTP的時候
get_cookies.ashx會拿到一堆亂碼 用其他方式登入的話就沒這個問題
會不會中間還有多甚麼動作出來需要執行的

**Comment by kevin940726** [comment]
Well Done!

亂碼應該跟encoding有關?
因為我剛剛也試了一下 Node
可以成功拿到otp
所以步驟應該不會有什麼變才對

**Comment by xnum** [comment]
thanks, it works.
https://github.com/xnum/BeanfunLogin/commit/61783b553a49a90d7402d551a7eb3baab28abf8e

**Comment by kevin940726** [comment]
I thinks it's better that you publish the new version. Feel free to make a new release when you are ready.
Let me know if there is any help needed! :smile:

**Comment by xnum** [comment]
so... shall we inject a ga script?

**Comment by kevin940726** [comment]
I think we should :joy:, also a re-connect feature would be nice.

**Comment by kevin940726** [comment]
Lets implement the features first, we can later implement the ga part once the features are ready.

**Comment by xnum** [comment]
Agree, which part will you implement?

**Comment by kevin940726** [comment]
Let me handle the re-connect part, can you push your code to this repo?

**Comment by xnum** [comment]
I created PR, but not sure if the operations are right, or you need `git push --force` to Development branch ?

**Comment by kevin940726** [comment]
Aren't you a collaborator? I thought that means you can push without sending the PR.

**Comment by kevin940726** [comment]
You can merge your own PR, or make a new `feature` branch.

**Comment by xnum** [comment]
done , merged into `Development` branch.
also removed some unsupported login method `Gamaotp` `otp` `聰明鎖`

**Comment by kevin940726** [comment]
I have recalled Why I wouldn't implement the auto-relogin feature..., I'm going to pass that feature.

I am surveying the best way to handle ga script, also I will add a new official page host on github page.

**Comment by xnum** [comment]
介意讓我知道為甚麼嗎 XDD

**Comment by kevin940726** [comment]
Sure XD
重新登入只有在一般登入時有用，而且這要建立在使用者有存帳號密碼的情況下，
假如像是你新增的 QRCode 等等其他登入方式就一定還是得手動登入，
所以我還是統一保留返回到登入畫面的方式處理這個問題，
另外我有注意到你有新增的 ping worker，
想問這個功能目前測試起來夠穩定嗎 ?

**Comment by xnum** [comment]
用蠻久了 蠻穩定的
 還可以知道是否被登出了
只是我沒有做那塊就是 或許可以延伸作個login status

**Comment by kevin940726** [comment]
嗯如果被登出了可以直接返回登入畫面，
這樣就也不會發生獲取密碼失敗的問題了

**Comment by xnum** [comment]
是 還有一些文章回應常見的excpetion例如connection failed
可以catch做個處理 以免使用者搞不清楚是甚麼錯誤
目前應該就沒有甚麼需要再更動的部分了

**Comment by kevin940726** [comment]
I have pushed a [commit](https://github.com/kevin940726/BeanfunLogin/commit/f98e965d3345821e9856e352b5a2b6e1d4a5c025) adding `CSharpAnalytics` to the project (it requires project target change to .NET 4.5, will it be a problem?)

Right now we basically capture some button and checkbox clicks and send them to the ga. Please review it for any additional usage.

Also I need your google email account for adding you to the ga collaborator.

**Comment by xnum** [comment]
我會想撈`login` `getotp`這兩個資料，藉由MD5或SHA1把帳號名稱、IP這些機密資訊轉換成不可還原的資料
這樣我們就可以知道：
1. 使用者平均擁有多少帳號
2. 帳號使用的登入方式統計
3. 每個帳號擁有多少遊戲帳號
4. 取得遊戲密碼的次數/availability (after GetOtpWorker_WorkCompeleted)
5. 每種登入方式的使用次數統計 (before loginButton_click)
至少統計4跟5我想比較沒有隱私問題 GA應該也可以做到1~3就不確定了

my email: s000032001@gmail.com
thx

**Comment by kevin940726** [comment]
我認為不應該把帳號名稱或甚至IP傳送到GA，
這樣危險性太大了我們也不應該拿到這麼隱私的資料

以上你說的五點都可以workaround

1. 只傳送有多少帳號，這樣就只是一個數字
2. 只傳送登入方式
3. 同1
4. 只傳送按鍵 event (同button event)
5. 同2

把分析和統計等等都在線下做
程式只傳送 raw data 給ga做記錄用

1~3 我覺得跟程式本身的改善比較無關
如果只是為了做粗略的統計我覺得不需要取得那麼詳細的資料
例如若是為了取得右邊的 account manager 使用情形可以只capture那些按鍵的event
可能還是要看你希望怎麼使用你說的這些資料吧?

已加入~ :smile:

**Comment by xnum** [comment]
的確有些只是我個人很好奇的統計資訊
最重要的有多少使用者在使用 這個目前code裡好像還沒有寫到

就程式面的話有兩點
一是 `獲取密碼` 現在有三種啟動方式 
1. 自行開啟遊戲 手動貼上
2. 自行開啟遊戲 自動貼上
3. 程式開啟遊戲
如果能知道這個分佈 或許可以移除一些使用率低的選項和功能
二是 `時間測量` ： `獲取密碼` 和 `登入` 根據不同登入方式
有可能出現伺服器沒有回應或等很久的情況
如果可以針對常出現delay的部分作UI優化 而不是把整個畫面hang住等待
應該會好一點

**Comment by kevin940726** [comment]
ga 自動涵蓋了使用者數量的問題這個有記錄到你可以上ga檢查一下

自動和手動貼上可以藉由判斷有沒有把自動輸入的 checkbox 打勾 (已implement)
而程式開啟或手動開啟遊戲也可以把判斷式篩在開啟遊戲的程式碼裡
假如已經有找到程式在運作代表是手動開啟
反之則是自動開啟

時間測量套件有相關的 [API](https://github.com/AttackPattern/CSharpAnalytics/wiki/Going-further#for-timing)
我覺得這個是沒有問題的
有興趣的話可以直接implement進去

你可以把你還想要統計的資料補齊
(或是做一個比較好管理的整理，我只先隨便命名了一下)
push 後做個總共統計了哪些事件的 list

**Comment by xnum** [comment]
ecf8b54 
3個timed track `Login`  `GetOTP` `FormLoad`
部分重新命名
錯誤處理改以exception track
另外有個bug 系統會自動觸發CheckChanged事件 推測是對Form或Panel修改時會觸發
例如KeepLogged按鈕已經隱藏 卻還是會有event track 這個我把他拿掉了
