### ISSUE TITLE
v1.9.1

### ISSUE THREAD

**Issue by kevin940726** [kevin940726/BeanfunLogin#19]
- [x] add ga script
- [x] QR Code login
- [x] remove outdated login method
- [x] new official landing page
- [x] merge development branch into master
- [x] better error handling

**Comment by kevin940726** [comment]
Except some more README text should be changed, the main features have been done. @xnum check it?

**Comment by xnum** [comment]
I saw it, cool! maybe we could have a CHANGELOG.md or CONTRIBUTING.md btw.
It's time to publish

**Comment by kevin940726** [comment]
Sure, can you review them and publish?

Note that we also have to update the version in README.md and zh-TW.md.

BTW I have no idea how to set up the proper update flow of the program, so it only check for updates with a fetch to the page (which it won't work now). Do you think we should change the function?

When you are all done, I will publish it to the article in the gamer forum.

**Comment by xnum** [comment]
Yes, I reviewed it. Is there anything I need to do or publish?

Since the frequency of update is very low and lots of mail will be send when the program doesn't work functionally, it won't be a problem whether the version update procedure really works, in my opinion.

**Comment by kevin940726** [comment]
I think that the update function need to change it's path (maybe to `./docs/index.md`) and the regexp.

Along with the readme files, I think that's all.

**Comment by xnum** [comment]
I forget privay policy announcement, I am going to write one later and create PR to let you review it.

**Comment by kevin940726** [comment]
OMG I almost forget it too...

**Comment by xnum** [comment]
Done, I committed it to `master` branch directly

**Comment by kevin940726** [comment]
I removed the content of `zh-TW.md`, are you going to edit the code in update function or should I do it?

**Comment by xnum** [comment]
no need for code fixing just keep the string `Version 1.9.1.`

**Comment by kevin940726** [comment]
Actually I mean [this part](https://github.com/kevin940726/BeanfunLogin/blob/master/BeanfunLogin/Form1.cs#L271)

**Comment by xnum** [comment]
ya add `Version 1.9.1` back to `zh-TW.md` or could you fix it because I noticed that some package config  and system settings are different from mine, it may take times to build compilation environment again, thanks.

**Comment by kevin940726** [comment]
OK Sure!

**Comment by kevin940726** [comment]
[v1.9.1](https://github.com/kevin940726/BeanfunLogin/releases/tag/v1.9.1)

Done!
