### ISSUE TITLE
1.9.1版錯誤

### ISSUE THREAD

**Issue by sky7st** [kevin940726/BeanfunLogin#20]
當開啟了一個登入器時
如果再開一個 會跳出例外錯誤
作業系統WIN10 PRO 其他無測試

**Comment by xnum** [comment]
請問開啟第二個登入器的時候，第一個登入器為已登入或未登入？
再開一個的時候，例外錯誤文字說明為合？是否能提供擷圖
程式中有針對帳號密碼進行加密，因此開啟多個時可能導致解密失敗跳出例外
如果是這個情況的話，這是無法被解決的問題

**Comment by sky7st** [comment]
先貼另外一個遇到的問題 原因未知
[圖片(imgur)](http://imgur.com/a/Rk5bA)

例外的詳細資料如下
如需叫用 Just-In-Time (JIT) 偵錯的詳細資料，
請參閱本訊息結尾處 (而非這個對話方塊) 的資訊。

************** 例外狀況文字 **************
System.Xml.XmlException: 有多個根元素。 行 1，位置 2。
   於 System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   於 System.Xml.XmlBaseReader.EnterScope()
   於 System.Xml.XmlUTF8TextReader.ReadStartElement()
   於 System.Xml.XmlUTF8TextReader.Read()
   於 System.Runtime.Serialization.XmlReaderDelegator.Read()
   於 System.Runtime.Serialization.XmlReaderDelegator.ReadEndElement()
   於 System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   於 System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   於 System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   於 System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   於 System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   於 System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)


************** 已載入的組件 **************
mscorlib
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BeanfunLogin
    組件版本: 1.9.1.0
    Win32 版本: 1.9.1.0
    程式碼庫: file:///D:/CHROMEDOWLOAD/BeanfunLogin/BeanfunLogin.exe
----------------------------------------
System.Windows.Forms
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
CSharpAnalytics.Net45
    組件版本: 1.2.0.0
    Win32 版本: 1.2.0.0
    程式碼庫: file:///D:/CHROMEDOWLOAD/BeanfunLogin/CSharpAnalytics.Net45.DLL
----------------------------------------
System.Core
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Runtime.Serialization
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Configuration
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Security
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Newtonsoft.Json
    組件版本: 9.0.0.0
    Win32 版本: 9.0.1.19813
    程式碼庫: file:///D:/CHROMEDOWLOAD/BeanfunLogin/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.ServiceModel.Internals
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.RunTime.Serialization.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/System.Runtime.Serialization.resources.dll
----------------------------------------
System.Net.Http
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
mscorlib.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.6.1586.0 built by: NETFXREL2
    程式碼庫: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 偵錯 **************
若要啟用 Just-In-Time (JIT) 偵錯功能，則必須在
此應用程式或電腦的 .config 檔案中，設定
system.windows.forms 區段內的 jitDebugging 值。
且該應用程式也必須在啟用偵錯的狀態下進行
編譯。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

當 JIT 偵錯功能啟用後，會將所有未處理的例外狀況
傳送給電腦上已註冊的 JIT 偵錯工具進行處
理，而不是使用這個對話方塊來處理。

**Comment by xnum** [comment]
推測是初始化時撈遊戲列表失敗
例外狀況文字下面還有更多訊息嗎
我在win10上面同時開啟多個沒有遇到這個問題

**Comment by sky7st** [comment]
沒有 就這些訊息
我好像經歷了一開始提到的問題之後
只要開啟新版登入器都會有後面那個問題發生
可是只要點繼續 仍然可以正常登入

**Comment by xnum** [comment]
試著重新下載 換個資料夾放看看

**Comment by sky7st** [comment]
試過了 相同結果

**Comment by xnum** [comment]
我想不出來可能的原因
如果您能順利取得遊戲列表 其他功能也沒出現問題
那就先這樣用吧 Q_Q

**Comment by xnum** [comment]
我大概猜到為什麼了 麻煩你尋找看看這兩個檔案
C:\Users\[你的使用者名稱]\AppData\Roaming\CSharpAnalytics-MeasurementQueue
C:\Users\[你的使用者名稱]\AppData\Roaming\CSharpAnalytics-MeasurementSession
並再關掉所有傳統登入器的情況下將這兩個檔案刪除 之後應該就不會出現這個情形
除非你又一次開多個 XD
