### ISSUE TITLE
打開沒有反應

### ISSUE THREAD

**Issue by EvenCu** [kevin940726/BeanfunLogin#21]
win10 1607
沒發現進程
rollback 1.8.1

**Comment by xnum** [comment]
我的win10沒有這個問題 有沒有可能被防毒砍掉
我只裝了windows defender

**Comment by kevin940726** [comment]
@xnum 有可能會跟.NET改成4.5有關嗎

**Comment by xnum** [comment]
如果是框架問題應該至少會跳個錯誤出來

**Comment by xnum** [comment]
@kevin940726 我有邀請你使用gitter 在討論上應該比較快
https://gitter.im/BeanfunLogin/Lobby

**Comment by EvenCu** [comment]
@xnum 一向裸奔的哦
.NET3.5 4.6都有

**Comment by xnum** [comment]
抓個1.9.2試試看 https://github.com/kevin940726/BeanfunLogin/releases

**Comment by EvenCu** [comment]
@xnum OK 可以囖
