### ISSUE TITLE
怎么打开猪头 显示不是有效的WIN32程序是 什么意思？

### ISSUE THREAD

**Issue by dongtingpj** [kevin940726/BeanfunLogin#25]
1. 作業系統版本： 
2. 是否安裝.net framework 4.5以上： (yes/no)
3. 程式資料夾是否有解壓縮出四個dll檔： (yes/no)
4. Beanfun網站是否能正常登入和啟動遊戲： (yes/no)
5. 是否已經依照上面兩個問與答嘗試排除問題： (yes/no)
6. 是否有防毒軟體跳出通知或偵測訊息： (yes/no)
7. 使用舊版是否能正常運作： (yes/no)
8. 是否刪除程式，重新下載v1.9.2還是出現問題： (yes/no)
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： (yes/no)
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：

**Comment by kevin940726** [comment]
內容都不回答的話實在很難幫你。

Close for now, feel free to reopen it when you fill up the form and ask question properly.

**Comment by dongtingpj** [comment]
我是XP系统
FRAMEWORK 4.0
有4个
能正常登陆
旧版的能登陆 我下载了新版 就删掉了谁知道新版登陆不上

**Comment by dongtingpj** [comment]
我好像上个版本是1.8.1吧 忘记了 有很久的  我这段时间才玩 那天都能登陆进去 但是后来提示有新版本 我就更行了 把以前的删了 谁知道打不开了
![qq 20170224193029](https://cloud.githubusercontent.com/assets/25949901/23302031/d5bdcaa6-fac7-11e6-8f3e-8b631364fb9d.png)
![qq 20170224193029](https://cloud.githubusercontent.com/assets/25949901/23302039/e4d81dc0-fac7-11e6-822a-0a45d539fb72.png)

**Comment by kevin940726** [comment]
你的問題就跟清單完全一樣，
現在需要 .NET framework 4.5 以上但你只有 4.0，
請去 [QA](https://kevin940726.github.io/BeanfunLogin/) 頁下載新版的 framework

**Comment by dongtingpj** [comment]
那个NET framework 4.5 不支持XP系统？
![qq 20170225184656](https://cloud.githubusercontent.com/assets/25949901/23330531/f2d4736a-fb8a-11e6-9914-950bc0cc545a.png)

**Comment by dongtingpj** [comment]
能把以前的1.8几的版本发个给我？

**Comment by kevin940726** [comment]
[網站](https://kevin940726.github.io/BeanfunLogin/)上面明明就有 **其餘各版本** 的連結呀 ...
