### ISSUE TITLE
UI的遊戲選擇部分

### ISSUE THREAD

**Issue by jaidTw** [kevin940726/BeanfunLogin#28]
順便提個建議，之前有同時開不同遊戲的需求，要切換時就必須反覆登出，重新選擇遊戲再登入
不知道UI設計上能不能改成先登入後再選擇遊戲取得帳號？

**Comment by xnum** [comment]
實作上應該可以做到 我會考慮加上這個
但目前UI有點擠 要再塞個下拉式選單會太滿
UI設計方面您有沒有什麼想法

**Comment by jaidTw** [comment]
我是覺得單純把下拉選單移到帳號頁的上方，切換時就reload，
然後記憶最後一次的選擇這樣改動最小，
不然就是多加一頁選擇遊戲(可能每個遊戲放一個button之類的)，點選遊戲後切到原本的帳號頁，然後帳號頁有返回鈕可以回去，選擇頁可以登出

**Comment by kevin940726** [comment]
之前有考慮過這件事，
因為這個程式一開始只有 target 在一款遊戲上所以當初設計沒有想那麼多，
PR welcome!

**Comment by zxc201314** [comment]
我是用ＭＡＣ 虛擬器(Parallels)開以前開嘟ＯＫ半年前
最近回來玩載1.9.3 怎麼點都無反應 去C:\Users都沒教學這兩個東西

**Comment by kevin940726** [comment]
@zxc201314 Please open another issue, and please be specific.

**Comment by anchi0221** [comment]
昨天UI有改動就想到這邊
有調整了一下位置  給你們參考一下
![ui](https://user-images.githubusercontent.com/43769516/46326464-63819780-c62f-11e8-8752-f31d1206dab7.png)

**Comment by xnum** [comment]
lgtm 有空改改看
