### ISSUE TITLE
登入延遲 以及異常

### ISSUE THREAD

**Issue by zxc97614** [kevin940726/BeanfunLogin#30]
1. 作業系統版本： W10
2. 是否安裝.net framework 4.5以上： (yes/no)是的
3. 程式資料夾是否有解壓縮出四個dll檔： (yes/no)是的
4. Beanfun網站是否能正常登入和啟動遊戲： (yes/no)是的
5. 是否已經依照上面兩個問與答嘗試排除問題： (yes/no)是的
6. 是否有防毒軟體跳出通知或偵測訊息： (yes/no)NO
7. 使用舊版是否能正常運作： (yes/no)YES
8. 是否刪除程式，重新下載v1.9.2還是出現問題： (yes/no)ＮＯ
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： (yes/no)ＮＯ
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：
你好昨天５／１７維修後　取得密碼以及登入Beanfunlogin 都要花上幾分鐘的時間 偶爾太久 會獲取失敗

**Comment by xnum** [comment]
已回覆於#500
https://forum.gamer.com.tw/Co.php?bsn=07650&sn=6136252&subbsn=0

**Comment by zxc97614** [comment]
謝謝大大的幫忙   看來就是橘子的問題了
