### ISSUE TITLE
取得密碼時間變長

### ISSUE THREAD

**Issue by lincw** [kevin940726/BeanfunLogin#31]
1. 作業系統版本： windowns 10
2. 是否安裝.net framework 4.5以上： yes
3. 程式資料夾是否有解壓縮出四個dll檔： yes
4. Beanfun網站是否能正常登入和啟動遊戲： yes
5. 是否已經依照上面兩個問與答嘗試排除問題： yes
6. 是否有防毒軟體跳出通知或偵測訊息： no
7. 使用舊版是否能正常運作： no
8. 是否刪除程式，重新下載v1.9.2還是出現問題： yes
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： yes
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：

取得單一帳號之密碼所需時間大約要 1 分鐘，比之前延遲很多。

**Comment by xnum** [comment]
Kevin 我覺得可能是伺服器程式有改版 您有什麼想法嗎

**Comment by kevin940726** [comment]
的確是變很久，這可能會需要重新確認伺服器端的流程有沒有改變，官網登入沒有異常嗎 ?

**Comment by xnum** [comment]
前幾天確認過都沒有改變
是在get_webstart_otp.ashx那條downloadstring 特別久

**Comment by xnum** [comment]
我解決這個問題了，預計今晚會release
