### ISSUE TITLE
獲取OTP碼的時候會等很久

### ISSUE THREAD

**Issue by mabipuromitheus** [kevin940726/BeanfunLogin#32]
1. 作業系統版本：  win7
2. 是否安裝.net framework 4.5以上：yes 
3. 程式資料夾是否有解壓縮出四個dll檔：yes 
4. Beanfun網站是否能正常登入和啟動遊戲： yes
5. 是否已經依照上面兩個問與答嘗試排除問題： yes
6. 是否有防毒軟體跳出通知或偵測訊息： no
7. 使用舊版是否能正常運作： no
8. 是否刪除程式，重新下載v1.9.2還是出現問題： 使用1.9.2 和1.9.3 都有問題
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： yes
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：

五月份開始, 部分帳號(好像是3-4月有經常性登入的那幾個)在使用登入器獲取OTP碼的時候會等很久(超過一分鐘), 但其他帳號則沒這個問題, 原因不明

**Comment by xnum** [comment]
我有收到您的信了
今晚已經有新版
請再試試

**Comment by mabipuromitheus** [comment]
您好

非常感謝! 沒問題了^^

Mabi player

2017-05-27 20:52 GMT+08:00 葉家郡 <notifications@github.com>:
