### ISSUE TITLE
顯示帳號密碼錯誤

### ISSUE THREAD

**Issue by kihei** [kevin940726/BeanfunLogin#34]
1. 作業系統版本： 
2. 是否安裝.net framework 4.5以上： yes
3. 程式資料夾是否有解壓縮出四個dll檔： yes
4. Beanfun網站是否能正常登入和啟動遊戲： no
5. 是否已經依照上面兩個問與答嘗試排除問題： yes
6. 是否有防毒軟體跳出通知或偵測訊息： no
7. 使用舊版是否能正常運作： no  
8. 是否刪除程式，重新下載v1.9.2還是出現問題： yes 會顯示憑證卡未插入訊息
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： yes
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：
我用筆電登入樂豆網頁是可以正常登入的，所以帳號密碼並沒有錯誤。另外，我試了一下，卡片後面數字開頭為7的卡片都會出現這個問題，而8開頭的就可以正常使用。顯示如下面的連結
https://user-images.githubusercontent.com/29270099/26915045-eb2a8ec0-4c56-11e7-8683-eafef06f1446.png

**Comment by xnum** [comment]
這個問題有點麻煩 因為我手上沒有7的卡
如果您願意幫忙測試的話請email聯繫

**Comment by xnum** [comment]
寫一下初步研究結果...

cardtype F或G不影響，網頁上的CheckOTP目前還沒有使用
檢查網頁的cab版本無更動
8系列免額外安裝驅動，但7系列要
初步懷疑是程式使用特定的dll問題
但是如何判讀或解決目前沒有找到

**Comment by kihei** [comment]
你好，我剛剛突然想到用筆電1.9.3版的試試，
結果是在筆電(win7)可以順利使用。
但把檔案拉到桌電(win10)就會變成憑證卡讀取失敗。

[image: 埋め込み画像 1]

2017-06-09 9:25 GMT+08:00 葉家郡 <notifications@github.com>:

**Comment by xnum** [comment]
假設在相容性已經勾選win7+管理員，卻仍然在win10出現此問題
那就跟作業系統有比較大的關係

1.9.4(和1.9.3) + win7(以及win10) 能正常使用嗎?
可否做個交叉測試縮小問題範圍

**Comment by kihei** [comment]
測試的結果是
1.9.4在筆電(win7)是沒有問題的

而在桌電(win10)即使勾選了win7相容性+管理員都不行
1.9.3版一樣是顯示憑證卡無法讀取
1.9.4版也一樣是帳號密碼錯誤

>
>

**Comment by xnum** [comment]
而您win10是可以透過BF網頁登入的是嗎?
這大概是個有點歷史的bug..因為PS登入很久沒修改過了

**Comment by kihei** [comment]
我的win10也是無法使用7開頭的卡登入網頁的
他都會顯示晶片卡無法讀取
但是我已經安裝晶片卡驅動了


2017-06-09 10:10 GMT+08:00 葉家郡 <notifications@github.com>:

**Comment by xnum** [comment]
那就跟驅動有關係了
建議先把原本的驅動移除後先安裝
https://tw.playsafecard.beanfun.com/BeanfunV3/plsf_ins_card7.aspx
還是不行的話就安裝這邊的
https://tw.playsafecard.beanfun.com/BeanfunV3/plsf_faq2.aspx
並且都以系統管理員身分進行安裝

**Comment by kihei** [comment]
這兩個都不行
使用硬體測試網頁他是有讀取到的
可是要登入的時候卻都沒辦法登入
[image: 埋め込み画像 1]
[image: 埋め込み画像 2]

2017-06-09 10:22 GMT+08:00 葉家郡 <notifications@github.com>:

**Comment by xnum** [comment]
這可能要寄信問橘子了
應該是官方那邊的問題或您的電腦有設定需要調整

**Comment by kihei** [comment]
恩，好的
非常謝謝你願意花這麼多時間幫我想辦法解決問題！



2017-06-09 10:45 GMT+08:00 葉家郡 <notifications@github.com>:

**Comment by dkalke** [comment]
如果是win10，
ie讀不到卡，
試試看換成這個驅動
Microsoft Usbccid Smartcard Reader (WUDF)

詳情請參考
https://m.gamer.com.tw/forum/Co.php?bsn=7650&snB=5301121
