### ISSUE TITLE
1.你好 請問一下 大大寫的 BeanfunLogin-v1.9.4  原始碼 我可以自己修改 嗎

### ISSUE THREAD

**Issue by candy60100** [kevin940726/BeanfunLogin#35]
1. 作業系統版本： 
2. 是否安裝.net framework 4.5以上： (yes/no)
3. 程式資料夾是否有解壓縮出四個dll檔： (yes/no)
4. Beanfun網站是否能正常登入和啟動遊戲： (yes/no)
5. 是否已經依照上面兩個問與答嘗試排除問題： (yes/no)
6. 是否有防毒軟體跳出通知或偵測訊息： (yes/no)
7. 使用舊版是否能正常運作： (yes/no)
8. 是否刪除程式，重新下載v1.9.2還是出現問題： (yes/no)
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： (yes/no)
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：

**Comment by xnum** [comment]
可以 有關此部分請參考MIT授權聲明
https://www.zhihu.com/question/25079718

**Comment by kevin940726** [comment]
請詳閱正式 [LICENSE](https://github.com/kevin940726/BeanfunLogin/blob/master/LICENSE.md) 文件
