### ISSUE TITLE
Asking for some tips

### ISSUE THREAD

**Issue by sky7st** [kevin940726/BeanfunLogin#37]
Hello, I'm trying to write a Beanfun OTP login with Python as a web crawler practice.
(Only on MapleStory)
But I couldn't understand how the login page actually works.
Could you please give me some tips or any point to start?
(I'm trying Beanfun login now but I couldn't find out the urls in your BeanfunClient.Login.cs )

**Comment by kevin940726** [comment]
Hi I recommended start from [`BeanfunClient.Login.cs`](https://github.com/kevin940726/BeanfunLogin/blob/master/BeanfunLogin/BeanfunClient.Login.cs) for the login part and then [`BeanfunClient.OTP.cs`](https://github.com/kevin940726/BeanfunLogin/blob/master/BeanfunLogin/BeanfunClient.OTP.cs) for the OTP part. What do you mean by the _urls_ ? For most of them, there are `DownloadString` as http GET and `UploadValues` as http POST, so just look for them in the code.

Hope that it help. 🙂

**Comment by sky7st** [comment]
Hello, After trying,I successfully got the AccountList but I had some problem.
First is although I counld get the AccountList, but before that I try on Line in  `BeanfunClient.Login.cs`

`payload.Add("SessionKey", skey); `
`payload.Add("AuthKey", akey);`
`response = Encoding.UTF8.GetString(this.UploadValues("https://tw.beanfun.com/beanfun_block/bflogin/return.aspx", payload));` 

when I send POST and skey akey as params,it requests no AuthKey to me.
Is there any requests header for the pages?(I didn't use any header but i got the AccountList)
----
The second is that After getting the AccountList, I try on  `BeanfunClient.OTP.cs`
but I had problem on getting longPollingKey.Line 
`response = this.DownloadString("https://tw.beanfun.com/beanfun_block/game_zone/game_start_step2.aspx?service_code="+service_code+"&service_region="+service_region+"&sotp=" + acc.sotp + "&dt=" + GetCurrentTime(2), Encoding.UTF8);`

always requests a beanfun error msg so I couldn't get the  longPollingKey and screatetime.
(btw:I can get the secretCode)

**Comment by kevin940726** [comment]
I think I should mentioned that we use a [custom HTTP client](https://github.com/kevin940726/BeanfunLogin/blob/master/BeanfunLogin/BeanfunClient.cs) for our requests. There are headers (such as `user-agent` which you might be missing) and cookies set under the hood. The implementation defer from language to language, but you can definitely implement it in python.

**Comment by sky7st** [comment]
Thanks for your reply.I'd add user-agent info in headers and send requests to
"https://tw.beanfun.com/beanfun_block/game_zone/game_start_step2.aspx?service_code="+service_code+"&service_region="+service_region+"&sotp=" + sotp + "&dt=" + currentTime

 but it didn't work.The return url is 

"https://tw.beanfun.com/utilities/common_err_page.htm?aspxerrorpath=/beanfun_block/game_zone/game_start_step2.aspx".

In addition, I'm using 
`res = requests.session()
----send requests to get skey   --success
----send requests to get akey  --success
----send requests to "https://tw.beanfun.com/beanfun_block/bflogin/return.aspx" --failed(returns no AuthKey )
----send requests to get AccountList --success
in these steps I didn't put any headers but I can get most of the data I need(skey,akey,bfWebToken,AccountList)
but it returns failed when I try to get  longPollingKey.
So I guests that something in my params is wrong.Maybe current time?
Are the milliseconds in current time important for the params?

**Comment by kevin940726** [comment]
I'm not sure since we have no knowledge of the actual implementation of beanfun backend, we only mimic the behavior of the browser and try to be as equal as possible. My guess is that maybe it's `cookie` issue or `redirect` issue. I suggest you look into them.

**Comment by sky7st** [comment]
Yep,I finally find out the problem. It's cookies right.I login and choose my game account.Then I copy the requests cookies to my code and it works. I find out that It only requires 3 cookies
1.ASP.NET_SessionId
2.bfWebToken(Is this the bfWebToken we get in BeanfunClient.Login.cs? )
3.bfTD(Is this bfTokenData?)

now, some new problems. 
There're two ASP.NET_SessionId in cookies one is for .beanfun.com the other is for tw.newlogin.beanfun.com.Which is the correct one?
Btw. I actually try these two value,and the other needed cookies I got before my code, but some returns
url "https://tw.beanfun.com/utilities/common_err_page.htm?aspxerrorpath=/beanfun_block/game_zone/game_start_step2.aspx"
some returns "https://tw.beanfun.com/beanfun_block/utilities/message_page.aspx?msgid=LOGIN-UNLOGIN_IN_PLEASE_LOGIN"
 I think I'm close to solve the promblem.Any suggestion please:)

**Comment by kevin940726** [comment]
We are getting cookie from [this domain](https://github.com/kevin940726/BeanfunLogin/blob/master/BeanfunLogin/BeanfunClient.cs#L88).
