### ISSUE TITLE
關於子行程

### ISSUE THREAD

**Issue by WeiZhiHuang** [kevin940726/BeanfunLogin#39]
1. 作業系統版本： Win 10 professional x64
2. 是否安裝.net framework 4.5以上： y
3. 程式資料夾是否有解壓縮出四個dll檔：y
4. Beanfun網站是否能正常登入和啟動遊戲： n
5. 是否已經依照上面兩個問與答嘗試排除問題： n
6. 是否有防毒軟體跳出通知或偵測訊息： n
7. 使用舊版是否能正常運作： y
8. 是否刪除程式，重新下載v1.9.3還是出現問題： y
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： 沒有嘗試
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：一般正常流程

遊戲：新楓之谷
好啦 其實我要問的問題跟上面沒有關係 遊戲是可以正常啟動的 只是不能正常關閉
下次啟動就會被卡到 程式在開啟遊戲的時候會開啟兩個子行程(一個本體一個遊戲防護)
但是遊戲關閉後兩個子行程不一定會被關閉 有時候會關 有時候不會關
會變成下次要重開的時候會需要去工作管理員把兩個子行程關掉
taskkill的部分也有嘗試過 但是因為不能單砍子行程 還是只能手動砍

**Comment by xnum** [comment]
請跟官方反應
