### ISSUE TITLE
啓動報錯

### ISSUE THREAD

**Issue by thisisjin** [kevin940726/BeanfunLogin#41]
1. 作業系統版本： WIN10 1709 enterprise
2. 是否安裝.net framework 4.5以上： (yes)
3. 程式資料夾是否有解壓縮出四個dll檔： (yes)
4. Beanfun網站是否能正常登入和啟動遊戲： (yes)
5. 是否已經依照上面兩個問與答嘗試排除問題： (yes)
6. 是否有防毒軟體跳出通知或偵測訊息： (no)
7. 使用舊版是否能正常運作： (yes)
8. 是否刪除程式，重新下載v1.9.2還是出現問題： (yes)
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： (yes)
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：
![image](https://user-images.githubusercontent.com/22115417/34033527-890162a6-e1b5-11e7-9a0a-61056bae57e8.png)
不知道是不是appdata目錄下的config文件出錯還是別的問題。重新解壓也會這樣。

**Comment by xnum** [comment]
https://github.com/kevin940726/BeanfunLogin/releases/tag/v1.9.5

**Comment by thisisjin** [comment]
@xnum 你是接替了原作者的工作嘛。

**Comment by xnum** [comment]
幫忙維護 Collaborator
