### ISSUE TITLE
無法取得OTP密碼

### ISSUE THREAD

**Issue by SonicFancy** [kevin940726/BeanfunLogin#43]
1. 作業系統版本：  win7
2. 是否安裝.net framework 4.5以上： (yes/no) Y
3. 程式資料夾是否有解壓縮出四個dll檔： (yes/no) Y
4. Beanfun網站是否能正常登入和啟動遊戲： (yes/no) Y
5. 是否已經依照上面兩個問與答嘗試排除問題： (yes/no) N
6. 是否有防毒軟體跳出通知或偵測訊息： (yes/no) N
7. 使用舊版是否能正常運作： (yes/no) 未測試 不過感覺結果一樣
8. 是否刪除程式，重新下載v1.9.2還是出現問題： (yes/no) 未測試
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： (yes/no) 未測試
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：

應該是官方更改某些東西了

https://cdn.discordapp.com/attachments/268983785498869770/433210064191356929/1.jpg

**Comment by ganwen1994** [comment]
同問題。
