### ISSUE TITLE
艾爾之光 無法開啟遊戲

### ISSUE THREAD

**Issue by beanels01** [kevin940726/BeanfunLogin#47]
1. 作業系統版本： Windows10
2. 是否安裝.net framework 4.5以上： yes
3. 程式資料夾是否有解壓縮出四個dll檔：yes
4. Beanfun網站是否能正常登入和啟動遊戲：yes
5. 是否已經依照上面兩個問與答嘗試排除問題： yes
6. 是否有防毒軟體跳出通知或偵測訊息： no
7. 使用舊版是否能正常運作： no
8. 是否刪除程式，重新下載v1.9.2還是出現問題： yes
9. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： yes
10. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)：
登入到擷取帳號，目前這邊都還算正常沒問題
也可以進遊戲，Xigncode也會過
但是就是會卡在開始頁面，跳伺服器連線中斷
不知道是不是傳入的參數需要修正？
![default](https://user-images.githubusercontent.com/10736618/44001594-b13182a0-9e67-11e8-9343-813cfca121ad.png)
![default](https://user-images.githubusercontent.com/10736618/44001600-bb133322-9e67-11e8-9955-6f4586b08450.png)

**Comment by SonicFancy** [comment]
艾爾之光印象中是遊戲主程式的問題
所以用登入器開也無解 N年前就是這樣了

**Comment by xnum** [comment]
可以幫我測試看看v1.9.7-dev是不是可以運作
https://github.com/kevin940726/BeanfunLogin/releases/download/v1.9.7-dev/BeanfunLogin-v1.9.7-dev.zip

**Comment by SonicFancy** [comment]
我個人現在只有玩瑪奇 艾爾是之前有測試
跟登入器的程式沒有關係 只要沒有用BF網頁打開 就是到1F的畫面卡住

然後 1.9.7 目前嘗試打開瑪奇 按下取得密碼後 出現錯誤 錯誤詳細資料如下

如需叫用 Just-In-Time (JIT) 偵錯的詳細資料，
請參閱本訊息結尾處 (而非這個對話方塊) 的資訊。

************** 例外狀況文字 **************
System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 BeanfunLogin.main.getOtpWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   於 System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   於 System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)


************** 已載入的組件 **************
mscorlib
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3133.0 built by: NET472REL1LAST
    程式碼庫: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BeanfunLogin
    組件版本: 1.9.7.0
    Win32 版本: 1.9.7.0
    程式碼庫: file:///C:/Users/Sonic/Desktop/BeanfunLogin-v1.9.7-dev/BeanfunLogin.exe
----------------------------------------
System.Windows.Forms
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3130.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3151.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3130.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
CSharpAnalytics.Net45
    組件版本: 1.2.0.0
    Win32 版本: 1.2.0.0
    程式碼庫: file:///C:/Users/Sonic/Desktop/BeanfunLogin-v1.9.7-dev/CSharpAnalytics.Net45.DLL
----------------------------------------
System.Configuration
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3130.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3130.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3130.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3130.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
Accessibility
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Security
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3130.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Newtonsoft.Json
    組件版本: 10.0.0.0
    Win32 版本: 10.0.2.20802
    程式碼庫: file:///C:/Users/Sonic/Desktop/BeanfunLogin-v1.9.7-dev/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.ServiceModel.Internals
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3130.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.RunTime.Serialization.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/System.Runtime.Serialization.resources.dll
----------------------------------------
System.Net.Http
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3130.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
mscorlib.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 偵錯 **************
若要啟用 Just-In-Time (JIT) 偵錯功能，則必須在
此應用程式或電腦的 .config 檔案中，設定
system.windows.forms 區段內的 jitDebugging 值。
且該應用程式也必須在啟用偵錯的狀態下進行
編譯。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

當 JIT 偵錯功能啟用後，會將所有未處理的例外狀況
傳送給電腦上已註冊的 JIT 偵錯工具進行處
理，而不是使用這個對話方塊來處理。

**Comment by SonicFancy** [comment]
1.9.7 pre版 目前可以正常登入瑪奇 其他遊戲本人沒帳號 要請其他大大幫忙測試
