### ISSUE TITLE
賬號密碼錯誤（已輸入正確帳密）

### ISSUE THREAD

**Issue by leon960102** [kevin940726/BeanfunLogin#50]
1. 作業系統版本： 
2. 是否安裝.net framework 4.5以上： (yes)
3. Beanfun網站是否能正常登入和啟動遊戲： (yes)
4. 使用舊版是否能正常運作： (no)
5. 是否刪除程式，重新下載最新版還是出現問題： (yes)
6. 相容性選項以win7執行這個程式、並以系統管理員的身分執行此程式，仍然出現錯誤： (yes)
7. 請詳述操作流程(請盡量附擷圖，如有詳細資訊請一併複製回報)
已再三確認輸入的帳號密碼正確
使用相同密碼在beanfun官網可正常登入
新舊版本亦同，今日才發生，昨天正常運作。
![image](https://user-images.githubusercontent.com/43786494/46356632-b42bdb80-c695-11e8-9631-1d575ecab54c.png)

**Comment by xnum** [comment]
我的是正常的，請檢查sha256是否相同

名稱: BeanfunLogin.exe
大小: 77824 位元組 (0 MB)

SHA256: D0487828E76C616BC491823F4A83A585F0E03596EB189C6E10EBAF0CE777650B

**Comment by SonicFancy** [comment]
1.9.7 PRE版的SHA256不一樣 可能是造成無法登入的原因(?)

**Comment by xnum** [comment]
抓個sha256驗證工具 檢查你抓到的不是pre版

https://ithelp.ithome.com.tw/questions/10022631
