### ISSUE TITLE
能否新增對香港Beanfun的支援

### ISSUE THREAD

**Issue by pungin** [kevin940726/BeanfunLogin#6]
能否新增對香港Beanfun的支援以及在香港登入台灣Beanfun需要驗證進階認證訊息的支援?

**Comment by kevin940726** [comment]
嗨我從沒登過香港的bf，所以對於添加此功能也不知道會花多少時間，我會再研究看看，不過也也許並不會更新在這個版本上，謝謝你的建議。

**Comment by zy691357966** [comment]
我認為很重要...我會嘗試閱讀你的源代碼去進行修改..
